//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class GameController : IController
	{

		GameModel gameModel;
		GameBehav gameBehav;
		
		RemoteService remoteService;

		Action<string> callback;

		public GameController ()
		{
		}

		public void SetData(GameModel gameModel, GameBehav gameBehav, RemoteService remoteService) {
			this.gameModel = gameModel;
			this.gameBehav = gameBehav;			
			this.remoteService = remoteService;
		}

		public void Init(Action<string> callback) {
			this.callback = callback;

			Debug.Log("yes");
		}

		public void Update() {
		}

		public void Dispose() {
		}
	}
}